FROM golang:1.25

WORKDIR /app
 
## Install air
ENV PATH=$PATH:/go/bin
RUN go install github.com/air-verse/air@latest

## Install swag
RUN go install github.com/swaggo/swag/cmd/swag@latest
ENV PATH=$PATH:/go/bin

EXPOSE 8000

# baixa dependências e roda Air
CMD ["sh", "-c", "go mod download && air -c .air.toml", ]
