version: '3.8'

services:
  app:
    container_name: go_inventory_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    command: air -c .air.toml
    
  frontend:
    container_name: go_inventory_front
    build:
      context: ./frontend
      dockerfile: Dockerfile.front
    ports:
      - "3001:3000"   # porta 3001 no host -> 3000 dentro do container
    volumes:
      - ./frontend:/app
      - /app/node_modules  # evita conflito de node_modules
    stdin_open: true
    tty: true

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
