definitions:
  apiContracts.InventoryData:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      started_at:
        type: string
      status:
        type: string
      updated_at:
        type: string
      user:
        $ref: '#/definitions/apiContracts.UserData'
      user_id:
        type: integer
    type: object
  apiContracts.InventoryListResponse:
    properties:
      data:
        properties:
          inventories:
            items:
              $ref: '#/definitions/apiContracts.InventoryData'
            type: array
        type: object
    type: object
  apiContracts.InventoryResponse:
    properties:
      data:
        $ref: '#/definitions/apiContracts.InventoryData'
    type: object
  apiContracts.UserData:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  auth.AuthResponse:
    properties:
      refreshToken:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth.RefreshResponse:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
  auth.RefreshTokenRequest:
    properties:
      refreshToken:
        type: string
    required:
    - refreshToken
    type: object
  entities.PalletEntity:
    properties:
      created_at:
        type: string
      id:
        type: integer
      inventory_id:
        type: integer
      name:
        type: string
      palletRackId:
        type: integer
      palletRackName:
        type: string
      palletizedProduct:
        items:
          $ref: '#/definitions/entities.PalletizedProductEntity'
        type: array
      qr_code:
        type: string
      qr_code_url:
        type: string
      updated_at:
        type: string
    required:
    - inventory_id
    - name
    - palletRackId
    - palletRackName
    type: object
  entities.PalletRackEntity:
    properties:
      created_at:
        type: string
      id:
        type: integer
      inventory_id:
        type: integer
      location:
        type: string
      name:
        type: string
      pallets:
        items:
          $ref: '#/definitions/entities.PalletEntity'
        type: array
      total_capacity:
        type: integer
      updated_at:
        type: string
    required:
    - inventory_id
    - location
    - name
    - total_capacity
    type: object
  entities.PalletizedProductEntity:
    properties:
      created_at:
        type: string
      ean:
        type: integer
      id:
        type: integer
      inventory_id:
        type: integer
      palletID:
        type: integer
      quantity:
        type: integer
      updated_at:
        type: string
    required:
    - ean
    - quantity
    type: object
  entities.UserEntity:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  inventory.InventoryRequest:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  paletrack.PalletRackRequest:
    properties:
      location:
        type: string
      name:
        type: string
      totalCapacity:
        minimum: 1
        type: integer
    required:
    - location
    - name
    - totalCapacity
    type: object
  pallet.PalletRequest:
    properties:
      name:
        type: string
      palletRackId:
        type: integer
    required:
    - name
    - palletRackId
    type: object
  palletizedproduct.PalletizedProductRequest:
    properties:
      ean:
        type: integer
      quantity:
        type: integer
    required:
    - ean
    - quantity
    type: object
  user.UserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
host: localhost:8000
info:
  contact:
    email: joaoferrazp@gmail.com
    name: API Support
  description: It is system to manage pallets and related products.
  title: Go Inventory API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Data
        in: body
        name: userData
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.AuthResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login
      tags:
      - Authentication
  /api/v1/auth/refreshToken:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh Token
        in: body
        name: refreshToken
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.RefreshResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Refresh token
      tags:
      - Authentication
  /api/v1/inventories:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiContracts.InventoryListResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List all inventories
      tags:
      - Inventory
    post:
      consumes:
      - application/json
      parameters:
      - description: Inventory Data
        in: body
        name: inventory
        required: true
        schema:
          $ref: '#/definitions/inventory.InventoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/apiContracts.InventoryResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new inventory
      tags:
      - Inventory
  /api/v1/inventories/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Inventory ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiContracts.InventoryResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get inventory by ID
      tags:
      - Inventory
  /api/v1/pallet/products/{palletId}:
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID do pallet
        in: path
        name: palletId
        required: true
        type: integer
      - description: Palletized Product
        in: body
        name: pallet
        required: true
        schema:
          $ref: '#/definitions/palletizedproduct.PalletizedProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.PalletizedProductEntity'
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add a product to a pallet
      tags:
      - Palletized products
  /api/v1/pallet/products/{palletId}/{productsEan}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID do pallet
        in: path
        name: palletId
        required: true
        type: integer
      - description: EAN do produto
        in: path
        name: productsEan
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete product from pallet
      tags:
      - Palletized products
  /api/v1/pallets:
    get:
      consumes:
      - application/json
      parameters:
      - description: Filter by pallet rack ID
        in: query
        name: palletRackId
        type: integer
      - description: Filter by product EAN
        in: query
        name: ean
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.PalletEntity'
            type: array
        "404":
          description: Not Found
      summary: List pallets
      tags:
      - Pallets
    post:
      consumes:
      - application/json
      parameters:
      - description: Palletized Product
        in: body
        name: pallet
        required: true
        schema:
          $ref: '#/definitions/pallet.PalletRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.PalletEntity'
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create Pallet
      tags:
      - Pallets
  /api/v1/pallets/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Palletized Product
        in: body
        name: pallet
        required: true
        schema:
          $ref: '#/definitions/pallet.PalletRequest'
      - description: ID do pallet
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.PalletEntity'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete Pallet
      tags:
      - Pallets
    get:
      consumes:
      - application/json
      parameters:
      - description: ID do pallet
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.PalletEntity'
        "404":
          description: Not Found
      summary: Get pallet by ID
      tags:
      - Pallets
    patch:
      consumes:
      - application/json
      parameters:
      - description: Palletized Product
        in: body
        name: pallet
        required: true
        schema:
          $ref: '#/definitions/pallet.PalletRequest'
      - description: ID do pallet
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.PalletEntity'
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update Pallet
      tags:
      - Pallets
  /api/v1/pallets/export:
    get:
      consumes:
      - application/json
      parameters:
      - description: Filter by pallet rack ID
        in: query
        name: palletRackId
        type: integer
      - description: Filter by product EAN
        in: query
        name: ean
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
      summary: Export pallets to CSV file
      tags:
      - Pallets
  /api/v1/racks:
    get:
      consumes:
      - application/json
      parameters:
      - description: Palletized Product
        in: body
        name: PalletRack
        required: true
        schema:
          $ref: '#/definitions/paletrack.PalletRackRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.PalletRackEntity'
            type: array
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List Pallet Racks
      tags:
      - Pallet Racks
    post:
      consumes:
      - application/json
      parameters:
      - description: Palletized Product
        in: body
        name: PalletRack
        required: true
        schema:
          $ref: '#/definitions/paletrack.PalletRackRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.PalletRackEntity'
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create Pallet Racks
      tags:
      - Pallet Racks
  /api/v1/racks/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID do Rack
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: Delete successful
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete Rack
      tags:
      - Pallet Racks
    get:
      consumes:
      - application/json
      parameters:
      - description: ID do Rack
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.PalletRackEntity'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Rack
      tags:
      - Pallet Racks
  /api/v1/users/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.UserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.UserEntity'
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create User
      tags:
      - Users
swagger: "2.0"
